apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Tamaño del volumen (ajusta según necesites)
  storageClassName: standard  # Usa el storage class predeterminado de Minikube